#!/usr/bin/env bash
# User-local (no-root) installer for Task Deck.
#
# Why this exists: pointing a .desktop file straight at the dev checkout is
# fragile — move or rename the repo and the Start-menu / KRunner entry breaks
# silently. Properly installed software decouples the *run location* from the
# *source*: data lives at stable XDG paths and only a thin launcher knows where
# the code is. This script does exactly that, entirely under $HOME (no sudo):
#
#   ~/.local/bin/taskdeck                          — launcher shim (knows the repo path)
#   ~/.local/share/icons/hicolor/scalable/apps/    — icon (theme-resolved)
#   ~/.local/share/applications/taskdeck.desktop   — menu entry (stable Exec/Icon)
#
# The repo path is baked ONLY into the shim. Move the repo → re-run this script;
# the .desktop never changes. Re-running is also how you "update" after a git
# pull (the app runs from the repo in place, so a pull is the update — this just
# refreshes the shim's path and the menu entry).
set -euo pipefail

# Resolve the repo root as the directory containing this script, so the install
# works no matter where the repo lives or what the current directory is.
REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
SHIM="$BIN_DIR/taskdeck"
DESKTOP="$APP_DIR/taskdeck.desktop"

mkdir -p "$BIN_DIR" "$ICON_DIR" "$APP_DIR"

# --- launcher shim: the ONE place the repo path lives ----------------------
# PYTHONPATH (not cd) so the app's working directory is the user's, matching
# how a normal installed program behaves. "$@" forwards any future CLI args.
cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# Task Deck launcher — generated by install.sh. Do not edit by hand; re-run
# install.sh from the repo to regenerate (e.g. after moving the repo).
export PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m taskdeck "\$@"
EOF
chmod +x "$SHIM"

# --- icon at a theme path so the .desktop can reference it by NAME ----------
cp -f "$REPO_DIR/assets/taskdeck.svg" "$ICON_DIR/taskdeck.svg"

# --- menu entry: stable paths only (absolute Exec, theme Icon name) ---------
# .desktop Exec does not expand ~ or $HOME, so the absolute shim path is
# written literally. $HOME is stable, so this line never needs to change.
cat > "$DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Task Deck
GenericName=systemd Task Scheduler
Comment=See and run your systemd timers and services
Exec=$SHIM
Icon=taskdeck
Terminal=false
Categories=System;Monitor;Qt;
Keywords=systemd;timer;service;task;scheduler;cron;job;unit;
EOF

# Best-effort cache refresh so the entry appears without a re-login. Both tools
# are optional; never fail the install if they are absent.
command -v update-desktop-database >/dev/null 2>&1 && \
    update-desktop-database "$APP_DIR" 2>/dev/null || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && \
    gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" 2>/dev/null || true

echo "Task Deck installed:"
echo "  launcher : $SHIM  ->  python3 -m taskdeck  (repo: $REPO_DIR)"
echo "  icon     : $ICON_DIR/taskdeck.svg"
echo "  menu     : $DESKTOP"
echo
echo "Launch from the application menu / KRunner ('Task Deck'), or run: taskdeck"
echo "(If 'taskdeck' is not found, add ~/.local/bin to PATH or use the full path above.)"
