#!/bin/bash
# Echoes a canned list-timers JSON document regardless of arguments.
echo '[{"next":1781136604691295,"left":1,"last":1781115051863104,"passed":1,"unit":"a.timer","activates":"a.service"}]'
